config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies, only: %i[index show] do
    post :import, on: :collection
  end

  resources :reviews, only: :index do
    post :import, on: :collection
  end
  resources :actors, only: :index
end

app/models/actor.rb
# frozen_string_literal: true

# Actor is a child of Artist, which is mapped with artists table having type Actor
class Actor < Artist
  validates :name, uniqueness: true
  scope :search_by_name, ->(search) { where('name ILIKE ?', "%#{search}%") if search.present? }
  # Ex:- scope :active, -> {where(:active => true)}
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
end

app/models/director.rb
# frozen_string_literal: true

# Director is a child of Artist, which is mapped with artists table having type Director
class Director < Artist
  has_many :movies
  accepts_nested_attributes_for :movies, allow_destroy: true
  validates :name, uniqueness: true
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  validates :city, uniqueness: { scope: :country }
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  belongs_to :director
  belongs_to :location
  has_many :movie_actors
  has_many :actors, through: :movie_actors

  validates :name, uniqueness: true
end

app/models/movie_actor.rb
# frozen_string_literal: true

class MovieActor < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
  validates :movie_id, uniqueness: { scope: :actor_id }
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :reviews
end

app/controllers/actors_controller.rb
# frozen_string_literal: true

# Actors actions
class ActorsController < ApplicationController
  def index
    @actors = Actor.search_by_name(params[:search])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

# Movies actions
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show]

  def index
    @movies = Movie.all.includes(:director)
  end

  def show; end

  def import
    service = ImportMoviesService.new(params[:file])
    @result = service.call
  end

  private

  def find_movie
    @movie = Movie.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

# Reviews actions
class ReviewsController < ApplicationController
  def index
    @reviews = Review.group(:stars).select(:stars, 'COUNT(*) as total').order(:total)
    @average_review = Review.average(:stars).round(2)
  end

  def import
    service = ImportReviewsService.new(params[:file])
    @result = service.call
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/actors/_actor.html.erb
<tr>
  <td><%= actor.name %></td>
</tr>

app/views/actors/_filters.html.erb
<%= form_tag actors_path, method: :get, class: 'row border p-3 m-1', remote: true do %>
  <div class="form-group">
    <%= text_field_tag :search, nil, placeholder: "search name", class: 'form-control' %>
  </div>
  <div class="row mt-2"><%= submit_tag "Search", class: 'btn btn-info w-50 m-auto' %></div>
<% end %>

app/views/actors/index.html.erb
<h1>Actors</h1>
<%= render 'filters' %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody id="actors">
    <%= render @actors %>
  </tbody>
</table>

app/views/actors/index.js.erb
$("#actors").html("<%= j (render @actors) %>")

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">#MOVIES#</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Movies", movies_path, class: "nav-item nav-link" %>
      <%= link_to "Actors", actors_path, class: "nav-item nav-link" %>
      <%= link_to "Reviews", reviews_path, class: "nav-item nav-link" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= render 'layouts/nav_bar' %>
      <div class="alert d-none" role="alert"></div>
      <%= yield %>
    </div>
    <%= render 'layouts/modal' %>
  </body>
</html>

app/views/movies/_import.html.erb
<%= form_tag "#{type}/import", multipart: true, class: 'border p-3 m-1', remote: true do %>
  <div class="form-group">
    <label> Upload CSV File </label>
    <%= file_field_tag :file, class: 'form-control', required: true, accept: 'text/csv' %>
  </div>
  <div class="row mt-2"><%= submit_tag "Import #{type}", class: 'btn btn-info w-50 m-auto' %></div>
<% end %>

app/views/movies/_movie.html.erb
<tr>
 <td><%= movie.name %></td>
 <td><%= movie.year %></td>
 <td><%= movie.director.name %></td>
 <td><%= link_to 'show', movie%></td>
</tr>

app/views/movies/import.js.erb
<% if @result == :success %>
  $(".alert").removeClass("d-none").removeClass("alert-danger")
  $(".alert").addClass("alert-success").html("movies uploaded")
<% else %>
  $(".alert").removeClass("d-none").removeClass("alert-success")
  $(".alert").addClass("alert-danger").html("movies uploading has been failed")
<% end %>
setTimeout(function() {
  $('.alert').addClass('d-none');
},2000);

app/views/movies/index.html.erb
<div class='row m-3'>
  <div class="col-3 offset-6">
    <button id='import-movie' class='btn btn-success float-right'>Import movies</button>
  </div>
  <div class="col-3">
    <button id='import-review' class='btn btn-info float-right'>Import reviews</button>
  </div>
  <div id='import-form' class='d-none'>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Director</th>
      <th>#</th>
    </tr>
  </thead>
  <tbody>
    <%= render @movies %>
  </tbody>
</table>
<script>
$(document).ready(function(){
  $('#import-movie').click(function(){
    $("#import-form").html("<%= j (render 'import', type: 'movies') %>");
    $("#import-form").toggleClass('d-none')
  });

  $('#import-review').click(function(){
    $("#import-form").html("<%= j (render 'import', type: 'reviews') %>");
    $("#import-form").toggleClass('d-none')
  });
})
</script>

app/views/movies/show.html.erb
<div class="row">
  <div class="col"> <h5>Movie:</h5> <%= @movie.name %> </div>
  <div class="col"> <h5>Year:</h5> <%= @movie.year %> </div>
  <div class="col"> <h5>Director:</h5> <%= @movie.director.name %> </div>
</div>
<div class="row">
  <div class="col-12"><h5>Actors</h5></div>
  <% @movie.actors.each do |actor| %>
    <div class="col-4 pl-3"><%= actor.name %></div>
  <% end %>
</div>
<div class="row">
  <div class="col"> <%= @movie.description %> </div>
</div>

app/views/reviews/_review.html.erb
<tr>
  <td><%= review.stars %></td>
  <td><%= review.total %></td>
</tr>

app/views/reviews/import.js.erb
<% if @result == :success %>
  $(".alert").removeClass("d-none").removeClass("alert-danger")
  $(".alert").addClass("alert-success").html("reviews uploaded")
<% else %>
  $(".alert").removeClass("d-none").removeClass("alert-success")
  $(".alert").addClass("alert-danger").html("reviews uploading has been failed")
<% end %>
setTimeout(function() {
    $('.alert').addClass('d-none');
},2000);

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<h6>Summary</h6>
<table class="table">
  <thead>
    <tr>
      <th>Star</th>
      <th>Count</th>
    </tr>
  </thead>
  <tbody>
    <%= render @reviews %>
  </tbody>
</table>
<h6 class="mt-2 text-success">Average Review is <%= @average_review %></h6>